# Generated by Django 6.1 on 2026-08-12 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='factorysetting',
            name='app_version',
            field=models.CharField(default='Version 1.0.0', max_length=20),
        ),
        migrations.AddField(
            model_name='factorysetting',
            name='copyright_text',
            field=models.CharField(default='© 2026 Pandora Sweaters Ltd.', max_length=200),
        ),
        migrations.AddField(
            model_name='factorysetting',
            name='developer_credit',
            field=models.CharField(default='Designed & Developed by IE_Zearul', max_length=200),
        ),
    ]
