# Generated by Django 6.1 on 2026-08-12 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_buyer'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnitMachine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=100)),
                ('gauge', models.CharField(blank=True, max_length=20)),
                ('line_no', models.CharField(max_length=50)),
                ('machine_no', models.CharField(max_length=50)),
                ('line_mc_no', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
