# Generated by Django 6.1 on 2026-08-18 18:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_knitmachine'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KnittingOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_id', models.CharField(max_length=20, unique=True)),
                ('job_no', models.CharField(max_length=50, unique=True)),
                ('style_no', models.CharField(max_length=100)),
                ('po_numbers', models.TextField()),
                ('plan_pct', models.IntegerField(default=0)),
                ('gauge', models.CharField(blank=True, max_length=50, null=True)),
                ('kcd_date', models.DateField()),
                ('operations', models.TextField()),
                ('total_color', models.IntegerField(default=0)),
                ('total_lot', models.IntegerField(default=0)),
                ('total_size', models.IntegerField(default=0)),
                ('total_order_qty', models.IntegerField(default=0)),
                ('total_plan_qty', models.IntegerField(default=0)),
                ('total_weight_lbs', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('avg_weight_dz', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_fields', models.TextField(blank=True, null=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.buyer')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='KnittingColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_name', models.CharField(max_length=100)),
                ('lots', models.TextField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colors', to='core.knittingorder')),
            ],
        ),
        migrations.CreateModel(
            name='KnittingSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_name', models.CharField(max_length=50)),
                ('order_qty', models.IntegerField(default=0)),
                ('plan_qty', models.IntegerField(default=0)),
                ('size_wt_gm', models.IntegerField(default=0)),
                ('total_lbs', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('sort_order', models.IntegerField(default=0)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='core.knittingcolor')),
            ],
        ),
        migrations.CreateModel(
            name='PageApprover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_name', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SystemNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('link', models.CharField(blank=True, max_length=255, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
