# Generated by Django 6.1 on 2026-08-13 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_ordermaster_ordercolor_orderpo_ordersizebreakdown_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermaster',
            name='changed_fields',
            field=models.TextField(blank=True, null=True),
        ),
    ]
