# Generated by Django 6.1 on 2026-08-18 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_knittingorder_knittingcolor_knittingsize_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knittingorder',
            name='job_no',
            field=models.CharField(max_length=50),
        ),
    ]
