# Generated by Django 6.1 on 2026-08-18 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_knittingorder_job_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='knittingorder',
            name='reject_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
