# Generated by Django 6.1 on 2026-08-20 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_operator'),
    ]

    operations = [
        migrations.AddField(
            model_name='knittingsize',
            name='bundle_qty',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
