# Generated by Django 6.1 on 2026-08-24 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_knittingsize_bundle_qty'),
    ]

    operations = [
        migrations.AddField(
            model_name='operator',
            name='category',
            field=models.CharField(default='Regular', max_length=50),
        ),
        migrations.AddField(
            model_name='operator',
            name='cell_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='operator',
            name='machine_brand',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='operator',
            name='machine_no',
            field=models.TextField(blank=True, null=True),
        ),
    ]
