# Generated by Django 6.1 on 2026-08-24 15:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_operator_category_operator_cell_no_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KnittingIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_id', models.CharField(max_length=20, unique=True)),
                ('tc_no', models.CharField(max_length=50, unique=True)),
                ('job_no', models.CharField(max_length=50)),
                ('buyer_name', models.CharField(max_length=100)),
                ('style_no', models.CharField(max_length=100)),
                ('po_no', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=100)),
                ('size', models.CharField(max_length=50)),
                ('lot', models.CharField(max_length=100)),
                ('operation', models.CharField(max_length=100)),
                ('machine_no', models.CharField(blank=True, max_length=50, null=True)),
                ('line', models.CharField(blank=True, max_length=100, null=True)),
                ('shift', models.CharField(default='Day', max_length=20)),
                ('issue_qty', models.IntegerField(default=0)),
                ('issue_weight_lbs', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('delete_reason', models.TextField(blank=True, null=True)),
                ('print_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('issued_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.operator')),
            ],
        ),
    ]
