# Generated by Django 6.1 on 2026-08-30 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_knittingissue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='knittingcolor',
            name='lots',
        ),
        migrations.CreateModel(
            name='KnittingYarn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yarn_name', models.CharField(max_length=150)),
                ('consumption_pct', models.DecimalField(decimal_places=2, default=100.0, max_digits=5)),
                ('req_weight_lbs', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yarns', to='core.knittingcolor')),
            ],
        ),
        migrations.CreateModel(
            name='KnittingYarnLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lot_name', models.CharField(max_length=100)),
                ('allocated_lbs', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('yarn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lots', to='core.knittingyarn')),
            ],
        ),
    ]
