# Generated by Django 6.1 on 2026-08-30 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_knittingcolor_lots_knittingyarn_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='knittingyarn',
            name='allowance_pct',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='knittingyarn',
            name='consumption_pct',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='knittingyarn',
            name='req_weight_lbs',
            field=models.IntegerField(default=0),
        ),
    ]
