# Generated by Django 6.1 on 2026-08-30 15:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_knittingyarn_allowance_pct_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='YarnReceive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_id', models.CharField(max_length=20, unique=True)),
                ('job_no', models.CharField(max_length=50)),
                ('buyer_name', models.CharField(max_length=100)),
                ('style_no', models.CharField(max_length=100)),
                ('po_no', models.CharField(max_length=100)),
                ('plan_pct', models.IntegerField(default=0)),
                ('color', models.CharField(max_length=100)),
                ('yarn_name', models.CharField(max_length=150)),
                ('allowance_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('lot_name', models.CharField(max_length=100)),
                ('req_weight_lbs', models.IntegerField(default=0)),
                ('before_received_lbs', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('current_received_lbs', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_received_lbs', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('balance_lbs', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('received_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='YarnReceiveHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received_lbs', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('received_date', models.DateTimeField(auto_now_add=True)),
                ('receive_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='core.yarnreceive')),
                ('received_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
