# Generated by Django 6.1 on 2026-08-31 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_yarnreceive_yarnreceivehistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='knittingcolor',
            name='assort_ratio',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='knittingcolor',
            name='lot_allocation_json',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='knittingcolor',
            name='pack_type',
            field=models.CharField(default='Solid Size', max_length=50),
        ),
        migrations.AddField(
            model_name='knittingsize',
            name='body_weight',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='knittingsize',
            name='others_weight',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='knittingyarn',
            name='parent_yarn_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='knittingyarn',
            name='yarn_type',
            field=models.CharField(default='Main', max_length=50),
        ),
        migrations.AddField(
            model_name='knittingyarnlot',
            name='frontend_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
