# Generated by Django 6.1 on 2026-09-06 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_knittingcolor_assort_ratio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='knittingcolor',
            name='lot_rule',
            field=models.CharField(default='Fixed', max_length=20),
        ),
        migrations.AddField(
            model_name='knittingsize',
            name='operation_weights_json',
            field=models.TextField(blank=True, null=True),
        ),
    ]
