# Generated by Django 6.1 on 2026-09-07 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_knittingcolor_lot_rule_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='knittingsize',
            name='restricted_qty',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='knittingorder',
            name='plan_pct',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='yarnreceive',
            name='plan_pct',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
